### PR TITLE
begin conversion from centos:7 to alpine:3.3

### PR DESCRIPTION
**Pull request by sometheycallme**
@jumanjiman 

Conversion from Centos:7 to Alpine:3.3 beginning here :)

### CODE REVIEW

**Comment by sometheycallme** [comment]
https://pkgs.alpinelinux.org/packages?name=ansible&branch=&repo=&arch=&maintainer=

**Comment by sometheycallme** [comment]
Nice, apk add ansible pulls in the other deps.

```
Step 2 : RUN apk upgrade --no-cache --available &&     apk add --no-cache       ansible       python
 ---> Running in 09ad0cf4b6da
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
OK: 5 MiB in 11 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/19) Installing libbz2 (1.0.6-r4)
(2/19) Installing expat (2.1.1-r0)
(3/19) Installing libffi (3.2.1-r2)
(4/19) Installing gdbm (1.11-r1)
(5/19) Installing ncurses-terminfo-base (6.0-r6)
(6/19) Installing ncurses-terminfo (6.0-r6)
(7/19) Installing ncurses-libs (6.0-r6)
(8/19) Installing readline (6.3.008-r4)
(9/19) Installing sqlite-libs (3.9.2-r0)
(10/19) Installing python (2.7.11-r3)
(11/19) Installing yaml (0.1.6-r1)
(12/19) Installing py-yaml (3.11-r0)
(13/19) Installing gmp (6.1.0-r0)
(14/19) Installing py-crypto (2.6.1-r0)
(15/19) Installing py-ecdsa (0.13-r0)
(16/19) Installing py-paramiko (1.15.2-r0)
(17/19) Installing py-markupsafe (0.23-r0)
(18/19) Installing py-jinja2 (2.8-r0)
(19/19) Installing ansible (1.9.4-r0)
```

**Comment by sometheycallme** [comment]
https://github.com/fabaff/alpine-ansible

Interesting.

**Comment by jumanjiman** [comment]
if you're going to put BATS inside the container, you also need to `apk add bash`.

**Comment by sometheycallme** [comment]
> if you're going to put BATS inside the container, you also need to apk add bash.

This is a better pattern:

https://github.com/jumanjihouse/docker-aws/blob/master/circle.yml

**Comment by sometheycallme** [comment]
Alpine is working.

**Pull request merged**
