### PR TITLE
flake8: version 3.0.1 test #118 use legacy.api flake8

### PR DESCRIPTION
**Pull request by sometheycallme**

### CODE REVIEW

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_flake8v3` at revision 807db87b4c7b5033d72725c77c120779ae41d332 on 0d6c790606a7

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_flake8v3` at revision 3a6adaefd871e9ed26e648c658c0b50902395d84 on 0d6c790606a7

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_flake8v3` at revision 2753181e82095b163578747ee3efee589d9c9883 on 0d6c790606a7

**Comment by sometheycallme** [comment]
Okay, one at a time, fix the flake8v3 issues.

Code doc coverage (easy on), comment on functions.

Before we had 50% coverage.  Now we have 100% with these commits.

https://github.com/cleanerbot/ansible-security/pull/119/commits/3a6adaefd871e9ed26e648c658c0b50902395d84

 https://github.com/cleanerbot/ansible-security/pull/119/commits/2753181e82095b163578747ee3efee589d9c9883


```
==== ./test/unit/fixture.py ====


Report
======
19 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |1      |NC         |NC         |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |1      |NC         |NC         |100.00      |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|method   |2      |NC         |NC         |100.00      |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|function |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
```

**Comment by sometheycallme** [comment]
http://flake8.pycqa.org/en/latest/user/python-api.html

**Comment by sometheycallme** [comment]
interesting

```
flake8.main.application: INFO: Reporting errors
flake8.style_guide: DEBUG: Deciding if "E123" should be reported
flake8.style_guide: DEBUG: The user configured "E123" to be "Selected.Explicitly", "Ignored.Explicitly"
flake8.style_guide: DEBUG: "E123" will be "Decision.Ignored"
flake8.style_guide: DEBUG: Error(code='E123', filename='./helpful_files/play.py', line_number=60, column_number=5, text="closing bracket does not match indentation of opening bracket's line", physical_line='    )\n') is not inline ignored
flake8.style_guide: DEBUG: Deciding if "F821" should be reported
flake8.style_guide: DEBUG: The user configured "F821" to be "Selected.Explicitly", "Selected.Implicitly"
flake8.style_guide: DEBUG: "F821" will be "Decision.Selected"
flake8.style_guide: DEBUG: Error(code='F821', filename='./test/unit/flake8_tests.py', line_number=14, column_number=54, text="undefined name 'count'", physical_line='            output = "\\n".join(report.get_statistics(count))\n') is not inline ignored
flake8.main.application: INFO: Found a total of 2 violations and reported 1
--------------------- >> end captured logging << ---------------------
```

**Comment by sometheycallme** [comment]
okay 0a6a25f fixed it, and now there are some errors with the playbook execution.

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_flake8v3` at revision 0a6a25fa089e4c35394255db2306ac5892cee973 on a2905e417d46

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_flake8v3` at revision 2b7e6f627c142829c570ceb179bea1e83ff20fda on a2905e417d46

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_flake8v3` at revision 60c3b08c9a36c19b18bad8624b343adc605a3ac3 on a2905e417d46

**Comment by sometheycallme** [comment]
Nice.  

bats script/test_*.bats
1..7
ok 1 ansible-controller: Ansible 2.x is installed and running
ok 2 ansible-controller: Autostager staging directory for contributor branches is in path
ok 3 autostager: Autostager python script is in path
ok 4 ansible-controller: fixtures path is set for testing
ok 5 ansible-controller: fixtures playbook executes locally (in container)
ok 6 ansible-controller: webserver responds to curl and playbook executes remotely (outside container)
ok 7 mock-client: client play script is in path set for testing


Fixed this problem.

```
ubuntu@box1094:~/ansible-security$ docker run -t -i --entrypoint bash ansible-controller -c "cd /opt/ansible; ansible --version"
ERROR! Unexpected Exception: No module named yaml
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible", line 81, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 27, in <module>
    import yaml
```

**Comment by sometheycallme** [comment]
:ship:

@jumanjiman 

FYI - If you run into Flak8v3 issues elsewhere, there is a legacy api that needs to be used, and the function for reporting needs the report object passed to it.

**Comment by jumanjiman** [comment]
> FYI - If you run into Flak8v3 issues elsewhere, there is a legacy api that needs to be used, and the function for reporting needs the report object passed to it.

cool, thanks for the heads-up!

**Pull request merged**
