### PR TITLE
decouple ansible tests from autostager

### PR DESCRIPTION
**Pull request by sometheycallme**

### CODE REVIEW

**Comment by Jfach** [comment]
If there is a way to check that pip has the most recent/stable release, that would be nice, but I'm not sure that's what were aiming for just yet. This works for now though, since we are currently maintaining autostager.

**Comment by sometheycallme** [comment]
@Jfach 

Its not a problem, when we run the ```pip list``` command, we can check for a desired version number.  Right now all I'm doing is looking to see if it's present or not.

see output check

```shell
@test "autostager: latest version is installed" {		
  run docker run --volumes-from playbooks-data -t -i --entrypoint bash autostager -c "pip list | grep autostager"		
   [[ ${output} =~ autostager \0.\ ]]		
}
```

**Comment by sometheycallme** [comment]
I am so hating my wireless connection right now.

**Comment by sometheycallme** [comment]
from circle:

```
go: GOPATH entry is relative; must be absolute path: "= /go".
Run 'go help gopath' for usage.
```

**Comment by sometheycallme** [comment]
I'm closing this PR because it has nothing to do with what we're working on.

**Pull request closed without merging**
