### PR TITLE
ansible-security: add env_vars file for docker run

### PR DESCRIPTION
**Pull request by sometheycallme**

### CODE REVIEW

**Comment by sometheycallme** [comment]
#40

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_basedir` at revision ade53b0ef945c2f1a79ac2ab0b0fa72ae86ba943 on eca1bcb20c87

**Comment by sometheycallme** [comment]
This is a testing PR for Autostager

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_basedir` at revision ade53b0ef945c2f1a79ac2ab0b0fa72ae86ba943 on 9f822e229836

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_basedir` at revision ade53b0ef945c2f1a79ac2ab0b0fa72ae86ba943 on 79e7085066c3

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_basedir is dangerously behind upstream

**Comment by sometheycallme** [comment]
Nice - autostager is working well.

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_basedir` at revision ade53b0ef945c2f1a79ac2ab0b0fa72ae86ba943 on 2f0c8178bb22

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_basedir is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_basedir` at revision ade53b0ef945c2f1a79ac2ab0b0fa72ae86ba943 on 2f0c8178bb22

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_basedir is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_basedir` at revision ade53b0ef945c2f1a79ac2ab0b0fa72ae86ba943 on 2f0c8178bb22

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_basedir is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_basedir` at revision ade53b0ef945c2f1a79ac2ab0b0fa72ae86ba943 on 2f0c8178bb22

**Pull request closed without merging**
