### PR TITLE
add vpc dev playbook create vpc

### PR DESCRIPTION
**Pull request by sometheycallme**

### CODE REVIEW

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 17907ced01e02c22feff97d329fcf33b2729f424 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 1f1eb934efb768698ff6b38a28df0b0f7ad510c8 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision ec97c8181f31fe7d5759ebae733115eb3230602c on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision a114a5c6a239b5f9a586db9275cbb033a0b3ffbf on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 8f667b3fbae764172fa900dc0bb1b9eba5e49a99 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision eab5e9221881a5402669ab8307c576a0e64d57f2 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision b3b93829df6dae93ef6153e5fbe00f57f4f3e0dc on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 6383dce0c8c8a613b2b335fb1d4461acb955aff4 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision fa484202a75f0740c83cbb7acab573da1ab39415 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 2214b84db3eb70006d0d8a4566344bbdd85aca09 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision dfd4a942f1fb93948e834ee0d2cd2bee934beae1 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision bd5b3e1ea441037aef9244101fd33e0d1b1e1731 on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision b1679c3556fde317ac406dd1cbca79112153b1bf on 7a0aad53a787

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision b1679c3556fde317ac406dd1cbca79112153b1bf on 01a163db7b39

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision e85943f43ababe98c706683f8f082e00c80870cc on a977192a973d

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 17819cc69b14abbcd60d8098c93d9a99e85a28fe on 633ed55d0a04

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision d168f99a2fef7b84a8205bb06b89c27ce7e1f9b9 on 781d203045c2

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on fa71b4f04986

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on db8c8aff7536

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 25e158875dae

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 809a08be2295

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 280ccb681e90

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 9051d12665b7

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 8ea6abddb6d7

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 12e49fe2d675

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 12e49fe2d675

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 31d1f257548a

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 31d1f257548a

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 31d1f257548a

**Comment by kropped** [comment]
:boom: Unstaged since cleanerbot_build_vpc is dangerously behind upstream

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_build_vpc` at revision 0b8ee4189d1a378aaab141b4a0a631c9edfc43cb on 31d1f257548a

**Comment by sometheycallme** [comment]
abandon no rebase.

**Pull request closed without merging**
