### PR TITLE
webserver: updated initial server model

### PR DESCRIPTION
**Pull request by Jfach**
info: based off of expected data from client script

### CODE REVIEW

**Comment by Jfach** [comment]
still have more server-side enforcement to do

**Comment by Jfach** [comment]
TODO:
 - [ ] make a whitelist of flags
 - [ ] enforce flags which require arguments actually have them

**Comment by Jfach** [comment]
Mantainers Note: Do not merge!

**Comment by kropped** [comment]
:bell: Staged `Jfach_serverside` at revision f747882407a33a66855d771270d4f8e56322fee9 on 9f822e229836

**Comment by kropped** [comment]
:bell: Staged `Jfach_serverside` at revision f747882407a33a66855d771270d4f8e56322fee9 on 79e7085066c3

**Comment by sometheycallme** [comment]
We're staging .   Nice

**Pull request merged**
