### PR TITLE
remove shell=True and test

### PR DESCRIPTION
**Pull request by sometheycallme**

### CODE REVIEW

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision a1af2ff0bbe629f6b7603b0f521032fc2b99d4eb on b14bdef50ff9

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision a1af2ff0bbe629f6b7603b0f521032fc2b99d4eb on a1a33e5e5147

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision a1af2ff0bbe629f6b7603b0f521032fc2b99d4eb on 04eed66d7dbc

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision cb7e818fc1c1a1c55fb8e99d0ae64e5b5916099a on 04eed66d7dbc

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 939c53efff610ab9b746eed4127f87af4a0705a4 on 04eed66d7dbc

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 8e8ec892a48414cd919bfd1865b5490cb6d2f3c5 on 04eed66d7dbc

**Comment by sometheycallme** [comment]
```
{u'branch_name': u'subprocess', u'git_handle': u'cleanerbot', u'flags': [{u'flag': u'-i', u'argument': u'inventory'}], u'playbook': u'ansible-security/fixtures/etc/ansible/play_test.yml'}
ansible-security/fixtures/etc/ansible/play_test.yml
[{u'flag': u'-i', u'argument': u'inventory'}]
{u'flag': u'-i', u'argument': u'inventory'}
ERROR! the playbook: /opt/staging/cleanerbot_subprocess/ansible-security/fixtures/etc/ansible/play_test.yml could not be found
program output: 
ansible-playbook -i inventory /opt/staging/cleanerbot_subprocess/ansible-security/fixtures/etc/ansible/play_test.yml
/opt/staging/cleanerbot_subprocess
172.17.0.1 - - [23/Oct/2016 01:40:16] "POST /play HTTP/1.1" 200 -
```

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 6304ae9464ef7f7af0e5447215c8ac76e07992e1 on 04eed66d7dbc

**Comment by sometheycallme** [comment]
When shell=False

```
not ok 6 ansible-controller: webserver responds to curl and playbook executes remotely (outside container)
# (in test file script/test_ansible.bats, line 42)
#   `testoutput=$(curl -v -X POST -d '{"branch_name": "master", "git_handle": "cleanerbot", "flags": [{"flag": "-i", "argument": "inventory"}], "playbook": "ansible-security/fixtures/etc/ansible/play_test.yml"}' http://${ip}:${port}/play)' failed with status 52
```

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 6304ae9464ef7f7af0e5447215c8ac76e07992e1 on a10e7d0efd61

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision fe62e2cfcaba1986ca4d1ccc6a52ab510eb9b81c on 7d3538d738b3

**Comment by sometheycallme** [comment]
the issue here for the failing test seems to be that the fixtures directory is not staged

When I place the example playbook in the root, it executes without issues.

```
Listening on localhost:8080
{u'branch_name': u'subprocess', u'git_handle': u'cleanerbot', u'flags': [{u'flag': u'-i', u'argument': u'inventory'}], u'playbook': u'play_test.yml'}
play_test.yml
[{u'flag': u'-i', u'argument': u'inventory'}]
{u'flag': u'-i', u'argument': u'inventory'}
 [WARNING]: Host file not found: inventory
 [WARNING]: provided hosts list is empty, only localhost is available
program output: 
PLAY [local] *******************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************


ansible-playbook -i inventory /opt/staging/cleanerbot_subprocess/play_test.yml
/opt/staging/cleanerbot_subprocess
172.17.0.1 - - [23/Oct/2016 12:31:04] "POST /play HTTP/1.1" 200 -
```

**Comment by sometheycallme** [comment]
core@pipeline ~/ansible-security $ docker exec -i -t 59ba1f5909d7 bash


bash-4.3# pwd
/opt/staging/cleanerbot_subprocess/fixtures/etc/ansible

bash-4.3# ls
group_vars     inventory      play_test.yml  site.yml

**Comment by sometheycallme** [comment]
was specifying the repo name in the path.  not necessary.

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 62069449fa92e953fc1ef5109ae28f13d520069a on 7d3538d738b3

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 62069449fa92e953fc1ef5109ae28f13d520069a on 1004b3ade4a6

**Comment by sometheycallme** [comment]
what happens when shell=False?

```
{u'branch_name': u'subprocess', u'git_handle': u'cleanerbot', u'flags': [{u'flag': u'-i', u'argument': u'inventory'}], u'playbook': u'fixtures/etc/ansible/play_test.yml'}
fixtures/etc/ansible/play_test.yml
[{u'flag': u'-i', u'argument': u'inventory'}]
{u'flag': u'-i', u'argument': u'inventory'}
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 43964)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "webserver/server.py", line 42, in do_POST
    self.play()
  File "webserver/server.py", line 101, in play
    proc = subprocess.Popen(command, stdout=subprocess.PIPE, shell=False)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by sometheycallme** [comment]
http://stackoverflow.com/questions/23787338/python-popen-shell-false-causes-oserror-errno-2-no-such-file-or-directory

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 020c6692d4a1af58b4743b038ffb76a3932ccff7 on 1004b3ade4a6

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 020c6692d4a1af58b4743b038ffb76a3932ccff7 on 1c61ef1ae639

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 573e8103d74cb153bcaa99a7c9183bc95f6d1bb5 on 1c61ef1ae639

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 6b453dd8a46da36ab906dd956f2fac3d1c697008 on 1c61ef1ae639

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 52cbfff91102d8be1f72b04042e29a4a916553f5 on 1c61ef1ae639

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision b7a03798beaa8bf5756246a544a61de6b1efcbf2 on 1c61ef1ae639

**Comment by sometheycallme** [comment]
core@pipeline ~/ansible-security $ curl -v -X POST -d '{"branch_name": "subprocess", "git_handle": "cleanerbot", "flags": [{"flag": "-i", "argument": "inventory"}], "playbook": "fixtures/etc/ansible/play_test.yml"}' http://172.17.0.5:8080/play > test.txt
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 172.17.0.5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 172.17.0.5 (172.17.0.5) port 8080 (#0)
> POST /play HTTP/1.1
> Host: 172.17.0.5:8080
> User-Agent: curl/7.50.1
> Accept: */*
> Content-Length: 159
> Content-Type: application/x-www-form-urlencoded
> 
} [159 bytes data]
* upload completely sent off: 159 out of 159 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 200 
< PLAY [local] *******************************************************************
< skipping: no hosts matched
< 
{ [84 bytes data]
100   316    0   157  100   159    353    357 --:--:-- --:--:-- --:--:--   358
* Closing connection 0
core@pipeline ~/ansible-security $ cat test.txt | grep PLAY
PLAY RECAP *********************************************************************

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision b7a03798beaa8bf5756246a544a61de6b1efcbf2 on 3705173756be

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision b364c77e0cfcdb05eeb539df6eff81f7145d4ab3 on 3705173756be

**Comment by sometheycallme** [comment]
passed here
https://github.com/cleanerbot/ansible-security/pull/128

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision f6dc3c4b4a3846e779b9a435a7159d2e23e1a49c on 3705173756be

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 32cf24e4bdd38970c0fad44ee7469341d36c02da on 3705173756be

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 224e70418fb4319b4d1f739d49d3152bdfb4c029 on 3705173756be

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision d4c58433ef5723594008d22764349825628e1d64 on 3705173756be

**Comment by kropped** [comment]
:bell: Staged `cleanerbot_subprocess` at revision 201d7d9f20ebd11c6235dabd73907697054e4149 on 3705173756be

**Pull request merged**
