### PR TITLE
webserver: break up request handler into methods for clarity

### PR DESCRIPTION
**Pull request by jumanjiman**
Fix indentation to resolve cleanerbot/ansible-security/issues/98.

### CODE REVIEW

**Comment by kropped** [comment]
:bell: Staged `jumanjiman_cleanup` at revision 227dc76ad457c0325b859364a9e32bc776236518 on fa71b4f04986

**Comment by kropped** [comment]
:bell: Staged `jumanjiman_cleanup` at revision 227dc76ad457c0325b859364a9e32bc776236518 on db8c8aff7536

**Comment by kropped** [comment]
:bell: Staged `jumanjiman_cleanup` at revision 227dc76ad457c0325b859364a9e32bc776236518 on 25e158875dae

**Comment by sometheycallme** [comment]
Here are some steps for testing this beyond circle:

### step 1 

on the pipeline i cloned your Fork and branch, and used the build scripts to build the docker images against your fork.

```shell
core@pipeline ~ $ cd ansible-security/
core@pipeline ~/ansible-security $ git remote -v
origin  https://github.com/jumanjiman/ansible-security.git (fetch)
origin  https://github.com/jumanjiman/ansible-security.git (push)
core@pipeline ~/ansible-security $ 
core@pipeline ~ $../build_autostager.sh

# (on a separate shell)
core@pipeline ~ $../build_controller.sh

```

### step 2: your PR is staged after I build the pipeline

Autostager staged your PR:

```
=========================
    INIT PULL REQUEST    
=========================
Branch: cleanup
Clone URL: https://111a4a337a9e88bae7d98bfd4a781f4daabec9b2@github.com/jumanjiman/ansible-security.git
Base Dir: /opt/staging
Name: jumanjiman_cleanup
Upstream URL: https://111a4a337a9e88bae7d98bfd4a781f4daabec9b2@github.com/cleanerbot/ansible-security.git
Staging Dir: /opt/staging/jumanjiman_cleanup
```

### step 3: controller likes the changes

webserver does not bark about syntax errors:

```
Successfully built 312ca8d97556
Running the Ansible Controller (webserver) and run interactively
Listening on localhost:8080
```

### step 4: FAILS when I send it json

however, now when I send the JSON data the webserver doesn't respond at all (meaning, no logging, no processing of commands, etc.)

```
core@pipeline ~ $ curl -v -X POST -d '{"branch_name": "cleanup", "git_handle": "jumanjiman", "flags": [{"flag": "-i", "argument": "hosts"}], "playbook": "fixtures/etc/ansible/play_test.yml"}' http://172.17.0.6:8080/play
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 172.17.0.6...
* Connected to 172.17.0.6 (172.17.0.6) port 8080 (#0)
> POST /play HTTP/1.1
> Host: 172.17.0.6:8080
> User-Agent: curl/7.47.1
> Accept: */*
> Content-Length: 152
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 152 out of 152 bytes
* Empty reply from server
* Connection #0 to host 172.17.0.6 left intact
curl: (52) Empty reply from server
```

As a test for the ```requestHandler``` class, I purposely left off the .yml to try and force it to hit this:

```python
if not playbook.endswith('.yml'):
            self.send_response(400, 'bad playbook extension')
            return
```

### step 5: add logging and rebuild

Then I rebuilt the images (following step 1 above) with some added a logging statements to the newly created functions in your fork/branch - inside the class to see if they are getting hit:

It process the do_POST function, and the request_path, but doesn't seem to get to ```def play (self)``` after the request_path is processed.

logging

```
Running the Ansible Controller (webserver) and run interactively
Listening on localhost:8080



do_POST
request_path == /play
```

where am i logging?

```python
class RequestHandler(BaseHTTPRequestHandler):

    def alphafy(self, a_string):
        pattern = "[^a-z0-9_]"
        return re.sub(pattern, "_", a_string, flags=re.IGNORECASE)

    def do_POST(self):
        print "do_POST"
        request_path = self.path

        # handle the play endpoint
        if request_path == '/play':
            print "request_path == /play"
            self.play
        elif request_path == '/run':
            self.run

    def play(self):
        print "play"
        request_headers = self.headers
```

**Comment by sometheycallme** [comment]
I think ```self.play``` is the culprit here.

**Comment by kropped** [comment]
:bell: Staged `jumanjiman_cleanup` at revision 227dc76ad457c0325b859364a9e32bc776236518 on 809a08be2295

**Comment by kropped** [comment]
:bell: Staged `jumanjiman_cleanup` at revision 227dc76ad457c0325b859364a9e32bc776236518 on 280ccb681e90

**Comment by sometheycallme** [comment]
yeah the proper syntax was  ```self.play()```

I'll see if I can push to your PR.

**Comment by sometheycallme** [comment]
I'll merge and add the final fix.

**Comment by jumanjiman** [comment]
> yeah the proper syntax was self.play()

thx, my ruby and python get mixed up

**Pull request merged**
